name: Testing Configuration Variables

on: workflow_dispatch
env:
  cloud: google-cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say hello to Deb"
        run: echo "$Greeting $first_name is using $cloud with project ${{ vars.PROJECT_ID }}"
        env:
          first_name: Deb
